// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingAnalytics.Infrastructure.Context;

namespace TrackingAnalytics.Infrastructure.Migrations
{
    [DbContext(typeof(RecordContext))]
    partial class RecordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("TrackingAnalytics.Core.Models.RecordModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ip")
                        .HasColumnType("longtext");

                    b.Property<string>("path")
                        .HasColumnType("longtext");

                    b.Property<string>("query")
                        .HasColumnType("longtext");

                    b.Property<string>("referer")
                        .HasColumnType("longtext");

                    b.Property<string>("userAgent")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
